name: Auto Build, Publish, Releasing

on:
  workflow_dispatch:
    inputs:
      publishMaven:
        description: 'whether publish to the maven'
        required: true
        type: boolean
        default: true
      publishCurseForgeAndModrinth:
        description: 'whether publish to the curseforge and modrinth'
        required: true
        type: boolean
        default: true
      versionType:
        description: 'Version type for releases'
        required: false
        type: choice
        default: 'release'
        options:
          - release
          - beta
          - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    
    steps:
      # 更新到最新版本的actions
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'